- id: ensure-just
  name: Ensure just command runner is available
  description: Verify Just command runner is properly installed (uses bundled rust-just binary)
  entry: bash -c '$PWD/bin/just "$@"'
  language: system
  pass_filenames: false
  always_run: true

# - id: ensure-just
#   name: Ensure just command runner is available
#   description: Verify Just command runner is properly installed (uses bundled rust-just binary)
#   entry: run_just.py
#   language: script
#   pass_filenames: false
#   always_run: true
