- id: ensure-just-script
  name: Ensure just command runner is available
  description: Verify Just command runner is properly installed (uses bundled rust-just binary)
  entry: run_just.py
  language: script
  pass_filenames: false
  always_run: true

- id: ensure-just-system
  name: Ensure just command runner is available
  description: Verify Just command runner is properly installed (uses bundled rust-just binary)
  # Print the path to the just command
  entry: bash -c 'jx=$(python3 -c "import pathlib,sys;p=next(pathlib.Path(\"/pc/clone\").rglob(\"just\"));print(p)"); $jx $@'
  language: system
  pass_filenames: false
  always_run: true

# - id: ensure-just
#   name: Ensure just command runner is available
#   description: Verify Just command runner is properly installed (uses bundled rust-just binary)
#   entry: run_just.py
#   language: script
#   pass_filenames: false
#   always_run: true
