- id: ensure-just
  name: Ensure just command runner is available
  description: Verify Just command runner is properly installed (uses bundled rust-just binary)
  entry: python3 -c "import sys; raise Exception('\n'.join(sys.argv[1:]))" $(ls) "$@"
  language: system
  pass_filenames: false
  always_run: true

# - id: ensure-just
#   name: Ensure just command runner is available
#   description: Verify Just command runner is properly installed (uses bundled rust-just binary)
#   entry: run_just.py
#   language: script
#   pass_filenames: false
#   always_run: true
