- id: ensure-just-script
  name: Ensure just command runner is available
  description: Verify Just command runner is properly installed (uses bundled rust-just binary)
  entry: run_just.py
  language: script
  pass_filenames: false
  always_run: true

- id: ensure-just-system
  name: Ensure just command runner is available
  description: Verify Just command runner is properly installed (uses bundled rust-just binary)
  entry: |
    bash -c '
      jx=$(python3 -c "import pathlib,sys;p=next(pathlib.Path(\"/pc/clone\").rglob(\"just\"));print(p)");
      bindir=$(dirname "$jx");
      export PATH="$bindir:$PATH";
      $jx "$@";
    '
  language: system
  pass_filenames: false
  always_run: true

- id: ensure-just-cargo
  name: Ensure cargo is available
  description: Verify Cargo can be found
  entry: cargo -V
  language: system
  types: [rust]
  pass_filenames: false
  always_run: true

# - id: ensure-just
#   name: Ensure just command runner is available
#   description: Verify Just command runner is properly installed (uses bundled rust-just binary)
#   entry: run_just.py
#   language: script
#   pass_filenames: false
#   always_run: true
