- id: run-just-rust
  name: just
  description: Run bundled just binary, also provides Rust toolchain/cargo for use
  entry: pre_commit_just
  language: rust
  types: [rust]
  pass_filenames: false
  always_run: true

- id: run-just-script
  name: just
  description: Run bundled just binary
  entry: run_just.py
  language: script
  pass_filenames: false
  always_run: true

- id: verify-cargo-version
  name: cargo version
  description: Verify Cargo and run with version flag
  entry: cargo -V
  language: system
  types: [rust]
  pass_filenames: false
  always_run: true
